apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: netflix
  name: netflix
spec:
  containers:
  - image: registry.gitlab.com/netcon2/k8s-data/web
    name: netflix
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  imagePullSecrets:
     - name: netflix     
status: {}
