apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5naXRsYWIuY29tIjp7InVzZXJuYW1lIjoibmV4bmNvbW11bmljYXRpb24yMDIyIiwicGFzc3dvcmQiOiJOZXRjb25AMTIzIiwiYXV0aCI6ImJtVjRibU52YlcxMWJtbGpZWFJwYjI0eU1ESXlPazVsZEdOdmJrQXhNak09In19fQ==
kind: Secret
metadata:
  creationTimestamp: null
  name: netflix
type: kubernetes.io/dockerconfigjson
